### ISSUE TITLE
Social Media App

### ISSUE THREAD

**Issue by ShawnToubeau** [uptonm/placeholder-title#13]
Had an idea that we could create a social media app. Can mock functionality from apps like 
Facebook but implement our own spin on it. 
For example, we can see what music our friends are listening to by using the Spotify API
Thoughts?

**Comment by uptonm** [comment]
I like the idea, I actually have already messed around with this on one of my other repos and would love to do it better than before.

**Comment by ShawnToubeau** [comment]
What's the repo? I'll check it out later today!

**Comment by uptonm** [comment]
https://github.com/uptonm/social-media I just got through with authentication but I believe there are api routes for posts and comments as well

**Comment by uptonm** [comment]
@ShawnToubeau So a big thing to think about when developing a social media application is the following system you'd like to implement. Think of the two major options being:

- followers/following: i.e. Twitter/Instagram
- friends/connections: i.e. Facebook/LinkedIn

The first option is a lot easier to implement because every time a person adds or removes a follower, their own user document is the only one that is affected. This meaning that user 1 follows user 2 so the only change to make is to push user 2 to the end of user 1's friends array. And deletion is the same.

However with friendship based connections we would need to modify both people each time a change is made. 

I'd like to here your opinion on this before I address #18 and #21

**Comment by ShawnToubeau** [comment]
These are good points, I think for the sake of simplicity we should go with followers/following and down the road, if we're feeling up to it we can switch it out with friends/connects.

Doesn't Facebook (or some other social media app) allow the option for both? Or I know some offer a "connect" option and a subscribe option

**Comment by uptonm** [comment]
I believe facebook has the follow option for people who are using their social media as a form of business. Like the kind of people that have social media for promotion rather than watching cat videos.

**Comment by ShawnToubeau** [comment]
Oh okay, that makes more sense. What are your thoughts?

**Comment by uptonm** [comment]
I like the followers idea. Less probability for error when developing
